// Note: This file is autogenerated using "resources/gen-version.js" script and
// automatically updated by "npm version" command.

/**
 * A string containing the version of the test-scaffold library
 */
export const version = '17.0.0-alpha.3' as string;

/**
 * An object containing the components of the test-scaffold version string
 */
export const versionInfo = Object.freeze({
  major: 1 as number,
  minor: 0 as number,
  patch: 0 as number,
  preReleaseTag: 'alpha.1' as string | null,
});
